"""initial_schema

Revision ID: 6a19ae95e3ab
Revises: 
Create Date: 2025-12-30 09:39:04.338978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a19ae95e3ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False, comment='User-provided organization ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Organization name'),
    sa.Column('logo', sa.String(), nullable=True, comment='Path to organization logo file'),
    sa.Column('display_name', sa.String(length=7), nullable=False, comment='Short display name (max 7 characters)'),
    sa.Column('address', sa.String(), nullable=False, comment='Organization address'),
    sa.Column('country', sa.String(), nullable=False, comment='Country'),
    sa.Column('pincode', sa.String(), nullable=False, comment='Postal/PIN code'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False, comment="User-provided unique identifier (e.g., 'EMP-12345', 'DOC-001')"),
    sa.Column('name', sa.String(), nullable=False, comment='Full name of the person'),
    sa.Column('email', sa.String(), nullable=True, comment='Email address (optional)'),
    sa.Column('role', sa.String(), nullable=True, comment='Role in hospital (e.g., Doctor, Nurse, Patient)'),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=False, comment='User status (active/inactive)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Account creation timestamp'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this building belongs to'),
    sa.Column('name', sa.String(), nullable=False, comment="Building name (e.g., 'Main Hospital', 'Emergency Wing')"),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_building_name_org')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal database ID'),
    sa.Column('entity_id', sa.String(), nullable=False, comment='User-provided alphanumeric ID'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this entity belongs to'),
    sa.Column('type', sa.Enum('person', 'material', name='entitytype'), nullable=False, comment='Entity type: person or material'),
    sa.Column('name', sa.String(), nullable=True, comment='Optional entity name'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'organization_id', name='uq_entity_id_org')
    )
    op.create_index(op.f('ix_entities_entity_id'), 'entities', ['entity_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('untracked_threshold_seconds', sa.Integer(), nullable=False, comment='Seconds before tag is marked as lost/untracked'),
    sa.Column('smtp_host', sa.String(), nullable=True, comment='SMTP server host'),
    sa.Column('smtp_port', sa.Integer(), nullable=True, comment='SMTP server port'),
    sa.Column('smtp_username', sa.String(), nullable=True, comment='SMTP username (email address)'),
    sa.Column('smtp_password', sa.String(), nullable=True, comment='SMTP password or app password'),
    sa.Column('smtp_from_email', sa.String(), nullable=True, comment='Email address to send from'),
    sa.Column('smtp_from_name', sa.String(), nullable=True, comment='Display name for sent emails'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_settings_organization_id'), 'organization_settings', ['organization_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=True)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False, comment='Foreign key to buildings table'),
    sa.Column('floor_number', sa.Integer(), nullable=False, comment='Floor number (e.g., 1, 2, 3)'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_building_floor')
    )
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=4), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.String(), nullable=False, comment="BLE MAC address (e.g., 'E0:C0:74:C6:AD:C8')"),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this tag belongs to'),
    sa.Column('name', sa.String(), nullable=True, comment="Optional name for the tag (e.g., 'Tag A', 'Entity Tag 1')"),
    sa.Column('assigned_user_id', sa.String(), nullable=True, comment='Foreign key to users table (nullable for unassigned tags)'),
    sa.Column('assigned_entity_id', sa.Integer(), nullable=True, comment='Foreign key to entities table (nullable for unassigned tags)'),
    sa.Column('status', sa.Enum('active', 'offline', name='tagstatus'), nullable=False, comment='Tag status (active/offline)'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last time tag was detected (updated on every event)'),
    sa.CheckConstraint('(assigned_user_id IS NULL OR assigned_entity_id IS NULL)', name='check_single_assignment'),
    sa.ForeignKeyConstraint(['assigned_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this room belongs to'),
    sa.Column('floor_id', sa.Integer(), nullable=False, comment='Foreign key to floors table'),
    sa.Column('room_name', sa.String(), nullable=False, comment="Room name (e.g., 'Room 104', 'ICU-A') - unique within organization"),
    sa.Column('room_type', sa.String(), nullable=True, comment="Room type (e.g., 'ICU', 'Ward', 'ER', 'Operating Room')"),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name', 'organization_id', name='uq_room_name_org')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_organization_id'), 'rooms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_name'), 'rooms', ['room_name'], unique=False)
    op.create_table('anchors',
    sa.Column('anchor_id', sa.String(), nullable=False, comment="Unique anchor identifier (e.g., 'Room 101', 'Gateway-A')"),
    sa.Column('anchor_name', sa.String(), nullable=True, comment='Optional human-readable name for the anchor (can be common across organizations)'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this anchor belongs to'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Foreign key to rooms table (nullable for unassigned anchors)'),
    sa.Column('status', sa.Enum('active', 'offline', name='anchorstatus'), nullable=False, comment='Anchor status (active/offline)'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last time anchor reported data'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('anchor_id')
    )
    op.create_table('live_locations',
    sa.Column('tag_id', sa.String(), nullable=False, comment='Foreign key to tags table (primary key ensures one location per tag)'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='Organization this live location belongs to (for fast filtering)'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Current room (nullable if tag is lost or in unknown room)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp (auto-updated on modification)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_live_locations_organization_id'), 'live_locations', ['organization_id'], unique=False)
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False, comment='Foreign key to tags table'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Room where tag was located (nullable if room is deleted)'),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when tag entered this room'),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when tag exited this room (NULL if still in room)'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_id'), 'location_history', ['id'], unique=False)
    op.create_index('ix_location_history_tag_entered', 'location_history', ['tag_id', 'entered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_history_tag_entered', table_name='location_history')
    op.drop_index(op.f('ix_location_history_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_index(op.f('ix_live_locations_organization_id'), table_name='live_locations')
    op.drop_table('live_locations')
    op.drop_table('anchors')
    op.drop_index(op.f('ix_rooms_room_name'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_organization_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('tags')
    op.drop_table('staff_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organization_settings_organization_id'), table_name='organization_settings')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_entities_entity_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
