"""initial_schema

Revision ID: 7449f4b8efd1
Revises: 
Create Date: 2025-12-18 09:06:00.678363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7449f4b8efd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="Building name (e.g., 'Main Hospital', 'Emergency Wing')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal database ID'),
    sa.Column('patient_id', sa.String(), nullable=False, comment="Hospital patient identifier (e.g., 'PAT-001')"),
    sa.Column('name', sa.String(), nullable=False, comment='Full name of the patient'),
    sa.Column('age', sa.Integer(), nullable=False, comment='Patient age'),
    sa.Column('email', sa.String(), nullable=True, comment='Email address (optional)'),
    sa.Column('mobile_number', sa.String(), nullable=True, comment='Mobile phone number (optional)'),
    sa.Column('admission_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when patient was admitted'),
    sa.Column('discharge_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when patient was discharged (NULL if still admitted)'),
    sa.Column('status', sa.Enum('admitted', 'discharged', name='patientstatus'), nullable=False, comment='Patient status (admitted/discharged)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False, comment="User-provided unique identifier (e.g., 'EMP-12345', 'DOC-001')"),
    sa.Column('name', sa.String(), nullable=False, comment='Full name of the person'),
    sa.Column('email', sa.String(), nullable=True, comment='Email address (optional)'),
    sa.Column('role', sa.String(), nullable=True, comment='Role in hospital (e.g., Doctor, Nurse, Patient)'),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=False, comment='User status (active/inactive)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Account creation timestamp'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False, comment='Foreign key to buildings table'),
    sa.Column('floor_number', sa.Integer(), nullable=False, comment='Floor number (e.g., 1, 2, 3)'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_building_floor')
    )
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('tag_id', sa.String(), nullable=False, comment="BLE MAC address (e.g., 'E0:C0:74:C6:AD:C8')"),
    sa.Column('assigned_user_id', sa.String(), nullable=True, comment='Foreign key to users table (nullable for unassigned tags)'),
    sa.Column('assigned_patient_id', sa.Integer(), nullable=True, comment='Foreign key to patients table (nullable for unassigned tags)'),
    sa.Column('status', sa.Enum('active', 'offline', name='tagstatus'), nullable=False, comment='Tag status (active/offline)'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last time tag was detected (updated on every event)'),
    sa.CheckConstraint('(assigned_user_id IS NULL OR assigned_patient_id IS NULL)', name='check_single_assignment'),
    sa.ForeignKeyConstraint(['assigned_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False, comment='Foreign key to floors table'),
    sa.Column('room_name', sa.String(), nullable=False, comment="Unique room name (e.g., 'Room 104', 'ICU-A')"),
    sa.Column('room_type', sa.String(), nullable=True, comment="Room type (e.g., 'ICU', 'Ward', 'ER', 'Operating Room')"),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_name'), 'rooms', ['room_name'], unique=True)
    op.create_table('anchors',
    sa.Column('anchor_id', sa.String(), nullable=False, comment="Unique anchor identifier (e.g., 'Room 101', 'Gateway-A')"),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Foreign key to rooms table (nullable for unassigned anchors)'),
    sa.Column('status', sa.Enum('active', 'offline', name='anchorstatus'), nullable=False, comment='Anchor status (active/offline)'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last time anchor reported data'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('anchor_id')
    )
    op.create_table('live_locations',
    sa.Column('tag_id', sa.String(), nullable=False, comment='Foreign key to tags table (primary key ensures one location per tag)'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Current room (nullable if tag is lost or in unknown room)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp (auto-updated on modification)'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False, comment='Foreign key to tags table'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='Room where tag was located (nullable if room is deleted)'),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when tag entered this room'),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when tag exited this room (NULL if still in room)'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_id'), 'location_history', ['id'], unique=False)
    op.create_index('ix_location_history_tag_entered', 'location_history', ['tag_id', 'entered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_history_tag_entered', table_name='location_history')
    op.drop_index(op.f('ix_location_history_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_table('live_locations')
    op.drop_table('anchors')
    op.drop_index(op.f('ix_rooms_room_name'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('tags')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
