"""add_tag_assignment_tracking

Revision ID: af863773e4f2
Revises: a48d1fbb563b
Create Date: 2026-01-06 20:00:54.838549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'af863773e4f2'
down_revision: Union[str, None] = 'a48d1fbb563b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_tag_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique assignment record ID'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='Entity that had the tag assigned'),
    sa.Column('tag_id', sa.String(), nullable=False, comment='Tag that was assigned to the entity'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when tag was assigned to entity'),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when tag was unassigned (NULL if still assigned)'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_tag_assignments_current', 'entity_tag_assignments', ['entity_id', 'tag_id', 'unassigned_at'], unique=False)
    op.create_index(op.f('ix_entity_tag_assignments_id'), 'entity_tag_assignments', ['id'], unique=False)
    op.create_index('ix_entity_tag_assignments_temporal', 'entity_tag_assignments', ['entity_id', 'tag_id', 'assigned_at', 'unassigned_at'], unique=False)
    op.create_table('user_tag_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique assignment record ID'),
    sa.Column('user_id', sa.String(), nullable=False, comment='User that had the tag assigned'),
    sa.Column('tag_id', sa.String(), nullable=False, comment='Tag that was assigned to the user'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when tag was assigned to user'),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when tag was unassigned (NULL if still assigned)'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tag_assignments_current', 'user_tag_assignments', ['user_id', 'tag_id', 'unassigned_at'], unique=False)
    op.create_index(op.f('ix_user_tag_assignments_id'), 'user_tag_assignments', ['id'], unique=False)
    op.create_index('ix_user_tag_assignments_temporal', 'user_tag_assignments', ['user_id', 'tag_id', 'assigned_at', 'unassigned_at'], unique=False)
    # ### end Alembic commands ###

    # Data migration: Create assignment records for currently assigned tags
    # This ensures existing tag assignments are tracked going forward
    connection = op.get_bind()

    # For entities: Find tags currently assigned and create assignment records
    # Estimate assigned_at from earliest location history, fallback to current timestamp
    connection.execute(text("""
        INSERT INTO entity_tag_assignments (entity_id, tag_id, assigned_at, unassigned_at)
        SELECT
            t.assigned_entity_id,
            t.tag_id,
            COALESCE(
                (SELECT MIN(lh.entered_at)
                 FROM location_history lh
                 WHERE lh.tag_id = t.tag_id),
                CURRENT_TIMESTAMP
            ) as assigned_at,
            NULL as unassigned_at
        FROM tags t
        WHERE t.assigned_entity_id IS NOT NULL
    """))

    # For users: Find tags currently assigned and create assignment records
    connection.execute(text("""
        INSERT INTO user_tag_assignments (user_id, tag_id, assigned_at, unassigned_at)
        SELECT
            t.assigned_user_id,
            t.tag_id,
            COALESCE(
                (SELECT MIN(lh.entered_at)
                 FROM location_history lh
                 WHERE lh.tag_id = t.tag_id),
                CURRENT_TIMESTAMP
            ) as assigned_at,
            NULL as unassigned_at
        FROM tags t
        WHERE t.assigned_user_id IS NOT NULL
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tag_assignments_temporal', table_name='user_tag_assignments')
    op.drop_index(op.f('ix_user_tag_assignments_id'), table_name='user_tag_assignments')
    op.drop_index('ix_user_tag_assignments_current', table_name='user_tag_assignments')
    op.drop_table('user_tag_assignments')
    op.drop_index('ix_entity_tag_assignments_temporal', table_name='entity_tag_assignments')
    op.drop_index(op.f('ix_entity_tag_assignments_id'), table_name='entity_tag_assignments')
    op.drop_index('ix_entity_tag_assignments_current', table_name='entity_tag_assignments')
    op.drop_table('entity_tag_assignments')
    # ### end Alembic commands ###
